import { GameSpec } from '../../core/types/GameSpec';

/**
 * Validates a game specification generated by the AI Planner.
 * Ensuring the factory doesn't attempt to build an impossible configuration.
 */
export class SpecValidator {
  
  static validate(spec: any): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!spec.name || typeof spec.name !== 'string') errors.push("Missing or invalid 'name'");
    if (!spec.slug || typeof spec.slug !== 'string') errors.push("Missing or invalid 'slug'");
    if (!spec.genre) errors.push("Missing 'genre'");
    if (!spec.description) errors.push("Missing 'description'");
    
    if (!spec.graphics) {
      errors.push("Missing 'graphics' configuration");
    } else {
      if (!['realistic', 'low-poly', 'pixel-art', 'abstract', 'minimalist'].includes(spec.graphics.style)) {
        errors.push(`Invalid graphics style: ${spec.graphics.style}`);
      }
      if (!['WebGL2', 'WebGPU', 'Canvas2D', 'DOM'].includes(spec.graphics.renderer)) {
        errors.push(`Invalid renderer: ${spec.graphics.renderer}`);
      }
    }

    if (!spec.controls) {
      errors.push("Missing 'controls'");
    }

    if (!spec.mobile) {
      errors.push("Missing 'mobile' compatibility config");
    }

    if (!spec.performance || typeof spec.performance.targetFPS !== 'number') {
      errors.push("Missing 'performance.targetFPS'");
    }

    return {
      valid: errors.length === 0,
      errors
    };
  }

  static suggestFixes(errors: string[]): string {
    return errors.map(e => `- ${e}`).join('\n');
  }
}
