import fs from 'fs';
const file = 'd:/Web App - Aqua Blue/src/components/games/VideoPoker.tsx';
let content = fs.readFileSync(file, 'utf8');
content = content.replace('const user = useAuthStore(state => state.user);', 'const { profile } = useAuthStore();');
content = content.replace(/profile\?\.id/g, 'profile.id');
content = content.replace(/profile\?\.tokens/g, 'profile.tokens');
content = content.replace(/profile\.id \|\| ""/g, 'profile.id');
content = content.replace('betAmount: betAmount', 'betAmount: bet');
content = content.replace('earnedAmount: payout', 'earnedAmount: winAmount');
fs.writeFileSync(file, content);
