import fs from 'fs';
const file = 'd:/Web App - Aqua Blue/src/components/games/VideoPoker.tsx';
let content = fs.readFileSync(file, 'utf8');
content = content.replace(/\buser\b/g, 'profile');
content = content.replace(/profile\.id/g, 'profile?.id');
content = content.replace(/profile\.tokens/g, 'profile?.tokens');
content = content.replace(/profile\?\.\?\.id/g, 'profile?.id');
content = content.replace(/profile\?\.\?\.tokens/g, 'profile?.tokens');
content = content.replace(/userId: profile\?\.id/g, 'userId: profile?.id || ""');
content = content.replace(/secureUpdateTokens\(profile\?\.id/g, 'secureUpdateTokens(profile?.id || ""');
content = content.replace(/betAmount, earnedAmount/g, 'betAmount: bet, earnedAmount');
fs.writeFileSync(file, content);
