import { GameSpec } from '../types/GameSpec';
import * as fs from 'fs';
import * as path from 'path';

/**
 * AQUA SPIN FACTORY
 * GameGenerator: Converts a formal GameSpec into scaffolding code.
 */
export class GameGenerator {
  
  /**
   * Generates the React component shell for a given GameSpec.
   * This shell maps standard GameSDK hooks to the React lifecycle.
   */
  public static generateReactComponent(spec: GameSpec): string {
    const componentName = this.toPascalCase(spec.slug);
    
    return `import React, { useEffect, useRef } from 'react';
import { GameSDK } from '@/engine/sdk/GameSDK';
import { useGameStore } from '@/store/gameStore';

/**
 * ${spec.name}
 * Auto-generated by Aqua Spin Factory v2.0
 * Genre: ${spec.genre}
 * Engine: ${spec.graphics.renderer}
 */
export default function ${componentName}() {
  const containerRef = useRef<HTMLDivElement>(null);
  
  useEffect(() => {
    // 1. Initialize SDK Lifecycle
    GameSDK.Lifecycle.initialize('${spec.slug}', {
      quality: '${spec.graphics.quality || 'high'}',
      fps: ${spec.performance?.targetFPS || 60}
    });
    
    // 2. Setup Camera
    ${spec.camera ? `GameSDK.Camera.setCameraMode('${spec.camera.type}');` : '// No specific camera required'}
    
    // 3. Mount Logic (Engine specific)
    if (containerRef.current) {
      GameSDK.Lifecycle.start();
    }
    
    // 4. Cleanup
    return () => {
      GameSDK.Lifecycle.end('unmount');
    };
  }, []);

  return (
    <div className="game-container w-full h-full relative bg-${spec.ui?.theme === 'dark' ? 'black' : 'white'}">
      {/* Engine Mount Point */}
      <div ref={containerRef} className="w-full h-full" />
      
      {/* UI Overlay */}
      ${spec.ui?.overlay ? `<div className="absolute top-0 left-0 p-4">
        <h1 className="text-xl font-bold text-white">${spec.name}</h1>
      </div>` : ''}
    </div>
  );
}
`;
  }

  /**
   * Injects the generated component into the src directory and updates the registry.
   */
  public static scaffoldGame(spec: GameSpec, srcGamesDir: string): boolean {
    try {
      const componentCode = this.generateReactComponent(spec);
      const componentName = this.toPascalCase(spec.slug);
      const filePath = path.join(srcGamesDir, `${componentName}.tsx`);
      
      fs.writeFileSync(filePath, componentCode);
      console.log(`[GameGenerator] Scaffolded ${filePath}`);
      
      return true;
    } catch (e) {
      console.error('[GameGenerator] Scaffold failed', e);
      return false;
    }
  }

  private static toPascalCase(str: string): string {
    return str
      .split(/[-_]+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
  }
}
